### ISSUE TITLE
java.lang.NullPointerException with Bandyer SDK

### ISSUE THREAD

**Issue by mcatta** [Bandyer/Bandyer-Android-SDK#8]
Hello,

we are opening this issue because we are experiencing this kind of error in production, this is impacting an average of 250 users over 30 days, and the issue seems to be related to your SDK. Currently, we are using the latest version `3.7.3`.

We didn't find a way to reproduce this crash, it happens randomly inside the app, and seems not related to a specific OS Version:

44%
Android 13
17%
Android 10
16%
Android 11
13%
Android 12
10%
Other (3)

Could you help us to identify the problem, please? If you need other information feel free to ask.

Kind regards,
Marco

```
Fatal Exception: java.lang.Error: java.util.concurrent.ExecutionException: java.lang.NullPointerException
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

```
Caused by java.util.concurrent.ExecutionException: java.lang.NullPointerException
       at java.util.concurrent.FutureTask.report(FutureTask.java:123)
       at java.util.concurrent.FutureTask.get(FutureTask.java:193)
       at com.kaleyra.collaboration_suite_utils.observer.BaseObserverCollection.execute$lambda-2(BaseObserverCollection.kt:70)
       at com.kaleyra.collaboration_suite_utils.observer.BaseObserverCollection.$r8$lambda$ivt6LQJmJrPlNgu6-4HJJdsBG5I()
       at com.kaleyra.collaboration_suite_utils.observer.BaseObserverCollection$$ExternalSyntheticLambda1.run(:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by fede87** [comment]
Hi,

thank you for contacting us.

Is it possible to have a broader stacktrace (just to start understanding if this is happening during connection/call/etc)?
Were all the crash occurrences happening using v3.7.3?
In case the crash occurrences happened also with other versions than v3.7.3, could you please provide us the BandyerSDK affected versions?

Best,

**Comment by mcatta** [comment]
Hi @fede87 ,

unfortunately, we are not able to reproduce the error and we have only the firebase stack-traces, in addition to the previous ones we have this one.

We spotted the same issue with the previous version `3.6.2`.

```
Caused by java.lang.NullPointerException:
       at com.bandyer.communication_center.call_client.CallClient$internalConnect$1$1.invoke(CallClient.kt:2)
       at com.bandyer.communication_center.call_client.CallClient$internalConnect$1$1.invoke(CallClient.kt:1)
       at com.kaleyra.collaboration_suite_utils.observer.BaseObserverCollection$forEach$1.invoke(BaseObserverCollection.kt:41)
       at com.kaleyra.collaboration_suite_utils.observer.BaseObserverCollection$forEach$1.invoke(BaseObserverCollection.kt:41)
       at com.kaleyra.collaboration_suite_utils.observer.BaseObserverCollection.execute$lambda-2$lambda-1(BaseObserverCollection.kt:70)
       at com.kaleyra.collaboration_suite_utils.observer.BaseObserverCollection.$r8$lambda$UMDnEKGOs7bwHnoLlYtb_ifSfWA(BaseObserverCollection.kt)
       at com.kaleyra.collaboration_suite_utils.observer.BaseObserverCollection$$ExternalSyntheticLambda0.call(D8$$SyntheticClass)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at com.osama.firecrasher.FireLooper.run(FireLooper.kt:9)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```
